#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'apache2'
cookbook 'database'
cookbook 'devbox',
   :git => 'https://github.com/Voronenko/chef-developer_recipes'
cookbook 'git'   
cookbook 'hostsfile'
cookbook 'java'   
cookbook 'php'
cookbook 'mysql'
cookbook 'memcached'
cookbook 'nginx'
cookbook 'nodejs'
cookbook 'npm'
cookbook 'tomcat'
